<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Graphite.Controls</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="FileDialogs\LocationSelectionDialog.xaml" />
    <None Remove="FileDialogs\OpenDialog.xaml" />
    <None Remove="FileDialogs\SaveDialog.xaml" />
    <None Remove="SettingsControls\SettingsCard\SettingsCard.xaml" />
    <None Remove="SettingsControls\SettingsExpander\SettingsExpander.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250108002" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="SettingsControls\SettingsExpander\SettingsExpander.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="SettingsControls\SettingsCard\SettingsCard.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="SettingsControls\SettingsCardExpander\" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Button\GraphiteButton.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="FileDialogs\LocationSelectionDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="FileDialogs\SaveDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="FileDialogs\OpenDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
</Project>