// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Riverside.Graphite.Data.Core;

#nullable disable

namespace Riverside.Graphite.Data.Core.Migrations
{
    [DbContext(typeof(HistoryContext))]
    [Migration("20250102031459_History_Add_Collections")]
    partial class History_Add_Collections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Riverside.Graphite.Data.Core.DbCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection_Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateTime_Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HistoryItemId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Riverside.Graphite.Data.Core.Models.DbHistoryItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("last_visit_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("typed_count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.Property<int>("visit_count")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("Riverside.Graphite.Data.Core.DbCollection", b =>
                {
                    b.HasOne("Riverside.Graphite.Data.Core.Models.DbHistoryItem", null)
                        .WithMany("DbCollections")
                        .HasForeignKey("HistoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Riverside.Graphite.Data.Core.Models.DbHistoryItem", b =>
                {
                    b.Navigation("DbCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
